#!/bin/bash

function file_count() {
echo "Please insert the Directory Name"
read directoryname
local count=$( ls -l $directoryname | wc -l )
echo "The total number of files available in the $directoryname is: $count"
}
file_count
